export const products = [
  {
    id: 1,
    slug: "employee-scheduling-app",
    name: "Employee Scheduling App",
    description: "A digital solution that streamlines workforce scheduling, automates shift management, and optimizes employee availability for businesses.",
    longDescription: "Transform your workforce management with our intelligent scheduling system. Built for modern businesses, it combines AI-powered optimization with intuitive interfaces to make employee scheduling effortless.",
    features: ["AI-Powered Scheduling", "Real-time Updates", "Mobile Access", "Integration APIs"],
    tech: ["NextJS", "Tailwind CSS", "Python", "Pytorch", "Django", "PostgreSQL", "Vercel", "Transfer Learning"],
    coverImage: "/case-studies/www.png",
    images: [
      "/case-studies/www/www-1.png",
      "/case-studies/www/www-2.png",
      "/case-studies/www/www-3.1.png",
      "/case-studies/www/www-3.png",
      "/case-studies/www/www-4.png",
      "/case-studies/www/www-5.png",
      "/case-studies/www/www-6.png",
    ],
    mission: "Empowering businesses to optimize their workforce and drive growth.",
    vision: "To become the leading provider of innovative workforce management solutions.",
    category: "Ventures",
    company: "OonkoO",
    companyLogo: "/oonkoo-dev.svg",
    link: "https://whoworkswhen.com"
  },
  {
    id: 2,
    slug: "dooh-advertising-platform",
    name: "DOOH Advertising Platform",
    description: "A platform designed to manage and deliver digital out-of-home advertising content across various screens and locations including mobile app.",
    longDescription: "Revolutionize outdoor advertising with our comprehensive DOOH platform. Reach your audience with targeted, dynamic content across multiple locations and formats.",
    features: ["AI Integration", "Real-time Analytics", "Automated Scheduling", "Location Targeting", "Multi Tenant"],
    tech: ["NextJS", "Tailwind CSS", "Python", "Pytorch", "Django", "PostgreSQL", "Vercel", "Transfer Learning"],
    coverImage: "/case-studies/ad-iq-app.jpg",
    images: [
      "/case-studies/ad-iq.png",
      "/case-studies/ad-iq-app.jpg",
      "/case-studies/ad-iq/ad-iq.png",
      "/case-studies/ad-iq/ad-1.png",
      "/case-studies/ad-iq/ad-2.png",
      "/case-studies/ad-iq/ad-3.png",
      "/case-studies/ad-iq/ad-4.png",
      "/case-studies/ad-iq/aq-1.jpg",
      "/case-studies/ad-iq/aq-2.png",
      "/case-studies/ad-iq/aq-3.jpg",
      "/case-studies/ad-iq/aq-4.png",
      "/case-studies/ad-iq/aq-5.png",
      "/case-studies/ad-iq/aq-6.png",
      "/case-studies/ad-iq/aq-7.png",
      "/case-studies/ad-iq/aq-8.png",
      "/case-studies/ad-iq/aq-9.png",
      "/case-studies/ad-iq/aq-10.png",
      "/case-studies/ad-iq/aph-1.png",
      "/case-studies/ad-iq/aph-2.png",
      "/case-studies/ad-iq/aph-3.png",
      "/case-studies/ad-iq/aph-4.png",
      "/case-studies/ad-iq/aph-5.png",
      "/case-studies/ad-iq/aph-6.png",
      "/case-studies/ad-iq/aph-7.png",
      "/case-studies/ad-iq/aph-8.png",
    ],
    mission: "Empowering businesses to optimize their workforce and drive growth.",
    vision: "To become the leading provider of innovative workforce management solutions.",
    category: "Enterprise Solutions",
    company: "City Group (AD-IQ)",
    companyLogo: "/partners/cg_l.png",
    link: "https://www.behance.net/gallery/123426619/AD-IQ-Listing-Website"
  },
  {
    id: 3,
    slug: "medical-ai-platform",
    name: "Medical AI Platform",
    description: "An advanced platform that utilizes AI to assist healthcare professionals in diagnosing, predicting, and personalizing treatment plans for patients.",
    longDescription: "",
    features: ["Custom Analytics", "AI Prediction", "Cross Platform", "User Management"],
    tech: ["NextJS", "Tailwind CSS", "Python", "Pytorch", "Django", "PostgreSQL", "Vercel", "Transfer Learning"],
    coverImage: "/case-studies/medicalprone.png",
    images: [
      "/case-studies/medicalprone.png",
      "/case-studies/mp/mp-1.png",
      "https://bmmk5ehvex.ufs.sh/f/m9mQBdJCZN5juFb75cHUL2WpeRJyh78139mEYzBaN5HQdCMO",
      "https://bmmk5ehvex.ufs.sh/f/m9mQBdJCZN5j8woy9WpUbcsmGt2wepWykl93LN8ErFaKonx1",
    ],
    mission: "Empowering businesses to optimize their workforce and drive growth.",
    vision: "To become the leading provider of innovative workforce management solutions.",
    category: "Medical Solutions",
    company: "City Group (Asgar Ali Hospital)",
    companyLogo: "/partners/cg_l.png",
    link: "https://medical-prone.vercel.app/"
  },
  {
    id: 4,
    slug: "lienzo-licensing-platform",
    name: "Lienzo - Licensing Platform",
    description: "Simplified software licenses management for businesses.",
    longDescription: "Lienzo is a comprehensive software license management platform designed to simplify the software licensing process for businesses.",
    features: ["Custom Analytics", "AI Prediction", "Cross Platform", "User Management"],
    tech: ["NextJS", "Tailwind CSS", "ShadCN/UI", "SQL"],
    coverImage: "/case-studies/lienzo.png",
    images: [
      "/case-studies/lienzo.png",
      "/case-studies/lienzo/l2.png",
      "/case-studies/lienzo/l3.png",
      "/case-studies/lienzo/l4.png",
      "/case-studies/lienzo/l5.png",
      "/case-studies/lienzo/l6.png",
      "/case-studies/lienzo/l7.png",
      "/case-studies/lienzo/l8.png",
      "/case-studies/lienzo/l9.png",
    ],
    mission: "At Lienzo, our mission is to empower organizations to take control of their software ecosystem. We strive to provide a comprehensive, user-friendly platform that transforms the way businesses acquire, manage, and optimize their software licenses.",
    vision: "To become the leading provider of innovative software asset management solutions.",
    category: "Enterprise Solutions",
    company: "Leinzo",
    companyLogo: "/partners/lienzo-logo.png",
    link: "https://lienzoapp.vercel.app/"
  },
  {
    id: 5,
    slug: "ontario-pulse-blogging-platform",
    name: "Ontario Pulse - Blogging Platform",
    description: "Your trusted source for Ontario news and updates.",
    longDescription: "Stay up-to-date with the latest news and updates from Ontario. Our platform provides a comprehensive and engaging experience for readers.",
    features: ["Static Generation", "MDX", "Cross Platform", "User Management"],
    tech: ["NextJS", "Tailwind CSS", "ShadCN/UI", "MDX"],
    coverImage: "/case-studies/op.png",
    images: [
      "/case-studies/op/op-2.png",
      "/case-studies/op/op-3.png",
      "/case-studies/op/op-1.png",
      "/case-studies/op/op-4.png",
      "/case-studies/op/op-5.png",
    ],
    mission: "Empowering readers with the latest news and updates from Ontario. Our mission is to provide a platform that is accessible, engaging, and informative.",
    vision: "To become the leading source of news and updates from Ontario.",
    category: "Ventures",
    company: "OonkoO",
    companyLogo: "/oonkoo-dev.svg",
    link: "https://www.ontariopulse.com"
  },
    {
    id: 6,
    slug: "orbanas-tech-partnership",
    name: "Orbanas - Tech Partnership",
    description: "Comprehensive technology partnership delivering white-label solutions, internal platforms, and client software development.",
    longDescription: "A strategic technology partnership with Orbanas, providing end-to-end technical solutions including white-label platform development, client software and website creation, design services, and ongoing platform maintenance.",
    features: ["White-Label Solutions", "Internal Platform Development", "Client Software", "Design Services", "Platform Maintenance"],
    tech: ["NextJS", "Tailwind CSS", "React", "TypeScript", "PostgreSQL"],
    coverImage: "/case-studies/orbanas.png",
    images: [
      "/case-studies/orbanas/orbanas-1.gif",
      "/case-studies/orbanas/orbanas-2.gif",
      "/case-studies/orbanas/orbanas-3.png",
      "/case-studies/orbanas/orbanas-4.gif",
      "/case-studies/orbanas/orbanas-5.gif",
    ],
    mission: "Empowering Orbanas with cutting-edge technology solutions to deliver exceptional value to their clients.",
    vision: "To be the trusted technology partner for innovative businesses seeking scalable solutions.",
    category: "Client Partnership",
    company: "Orbanas",
    companyLogo: "/partners/orbanas.svg",
    link: "https://www.orbanas.com"
  },
  {
    id: 7,
    slug: "elan-road-test-rental",
    name: "Elan Road Test Rental",
    description: "Complete business platform for Canadian G2/G driving instructors offering road test vehicle rental with certified instructors.",
    longDescription: "A comprehensive platform for Elan Road Test Rental featuring client and admin portals, Android and iOS mobile apps, automated payment processing, instructor auto-payment HR module, complete UI/UX design including logo and graphics, social media marketing, and targeted ad campaigns.",
    features: ["Client Portal", "Admin Portal", "Mobile Apps (iOS & Android)", "Automated Payments", "Instructor HR Module", "UI/UX Design", "Logo & Graphics", "Social Media Marketing", "Ad Campaigns"],
    tech: ["NextJS", "React Native", "Tailwind CSS", "TypeScript", "PostgreSQL", "Stripe", "Expo"],
    coverImage: "/case-studies/elan.png",
    images: [
      "/case-studies/elan/problem-statement.pdf",
      "/case-studies/elan/design-process.pdf",
      "/case-studies/elan/user-presona.pdf",
      "/case-studies/elan/user-journey.pdf",
      "/case-studies/elan/style-guide.pdf",
      "/case-studies/elan/info-architecture.pdf",
      "/case-studies/elan/ui-designs.pdf",
    ],
    mission: "Simplifying road test vehicle rental for Canadian driving instructors and students.",
    vision: "To become the leading platform for driving test preparation services in Canada.",
    category: "Client Partnership",
    company: "Elan",
    companyLogo: "/partners/elan.svg",
    link: "https://www.elanroadtestrental.ca/"
  },
  {
    id: 8,
    slug: "sopee-ai-sop-generator",
    name: "Sopee AI - SOP Generator",
    description: "AI-powered Statement of Purpose generation platform with custom fine-tuned models.",
    longDescription: "Sopee AI leverages custom fine-tuned AI models to generate high-quality Statement of Purpose letters for students and professionals. The platform streamlines the application process with intelligent content generation.",
    features: ["Custom AI Models", "Fine-tuned Generation", "Template Library", "Export Options", "Real-time Preview"],
    tech: ["NextJS", "Tailwind CSS", "Python", "OpenAI", "PostgreSQL", "Vercel"],
    coverImage: "/case-studies/sopee.png",
    images: [
      "/case-studies/sopee/sopee-1.png",
      "/case-studies/sopee/sopee-2.png",
      "/case-studies/sopee/sopee-3.png",
      "/case-studies/sopee/sopee-4.png",
      "/case-studies/sopee/sopee-5.png",
      "/case-studies/sopee/sopee-6.png",
      "/case-studies/sopee/sopee-7.png",
    ],
    mission: "Making professional SOP writing accessible to everyone through AI technology.",
    vision: "To revolutionize academic and professional application processes with AI-powered writing assistance.",
    category: "Ventures",
    company: "OonkoO",
    companyLogo: "/oonkoo-dev.svg",
    link: "https://sopee-ai.vercel.app/"
  },
  {
    id: 9,
    slug: "oonkoo-ui",
    name: "OonkoO UI",
    description: "React Tailwind UI component library for high-level websites with developer marketplace.",
    longDescription: "A comprehensive UI component library built with React and Tailwind CSS, featuring a marketplace where developers can upload and share their own components. Perfect for building modern, responsive websites quickly.",
    features: ["Component Library", "Developer Marketplace", "React & Tailwind", "Copy-Paste Components", "Customizable Themes", "Documentation"],
    tech: ["React", "Tailwind CSS", "TypeScript", "NextJS", "MDX"],
    coverImage: "/case-studies/oonkoo-ui.png",
    images: [
      "/case-studies/oonkoo-ui/oonkoo-ui-1.png",
      "/case-studies/oonkoo-ui/oonkoo-ui-2.png",
      "/case-studies/oonkoo-ui/oonkoo-ui-3.png",
      "/case-studies/oonkoo-ui/oonkoo-ui-5.gif",
      "/case-studies/oonkoo-ui/oonkoo-ui-4.png",
    ],
    mission: "Empowering developers to build beautiful interfaces faster with ready-to-use components.",
    vision: "To become the go-to component library for modern web development.",
    category: "Ventures",
    company: "OonkoO",
    companyLogo: "/oonkoo-dev.svg",
    link: "http://ui.oonkoo.com/"
  },
  {
    id: 10,
    slug: "kolom-ai-news-intelligence",
    name: "Kolom AI - News Intelligence",
    description: "Automated news platform with AI-powered scraping, summarization, and fact-checking.",
    longDescription: "Kolom AI is an intelligent news aggregation platform that scrapes news from multiple sources, uses AI models to summarize articles into concise 60-word summaries, categorizes content automatically, and performs fact-checking to ensure accuracy.",
    features: ["AI News Scraping", "60-Word Summaries", "Auto-Categorization", "Fact Checking", "Real-time Updates", "Multi-Source Aggregation"],
    tech: ["NextJS", "Python", "OpenAI", "Web Scraping", "NLP", "PostgreSQL", "Vercel"],
    coverImage: "/case-studies/kolom.png",
    images: [
      "/case-studies/kolom/kolom-1.png",
      "/case-studies/kolom/kolom-2.png",
      "/case-studies/kolom/kolom-5.gif",
      "/case-studies/kolom/kolom-3.png",
      "/case-studies/kolom/kolom-4.png",
    ],
    mission: "Delivering accurate, concise news summaries powered by AI to keep readers informed efficiently.",
    vision: "To become the most trusted AI-powered news platform for quick, verified information.",
    category: "Ventures",
    company: "OonkoO",
    companyLogo: "/oonkoo-dev.svg",
    link: "https://kolom.ai/"
  }
];