export const products = [
  {
    id: 1,
    name: "Employee Scheduling App",
    description: "A digital solution that streamlines workforce scheduling, automates shift management, and optimizes employee availability for businesses.",
    longDescription: "Transform your workforce management with our intelligent scheduling system. Built for modern businesses, it combines AI-powered optimization with intuitive interfaces to make employee scheduling effortless.",
    features: ["AI-Powered Scheduling", "Real-time Updates", "Mobile Access", "Integration APIs"],
    tech: ["NextJS", "Tailwind CSS", "Python", "Pytorch", "Django", "PostgreSQL", "Vercel", "Transfer Learning"],
    coverImage: "/products/www.png",
    images: [
      "/products/www/www-1.png",
      "/products/www/www-2.png",
      "/products/www/www-3.1.png",
      "/products/www/www-3.png",
      "/products/www/www-4.png",
      "/products/www/www-5.png",
      "/products/www/www-6.png",
    ],
    mission: "Empowering businesses to optimize their workforce and drive growth.",
    vision: "To become the leading provider of innovative workforce management solutions.",
    category: "Ventures",
    company: "OonkoO",
    companyLogo: "/oonkoo_logo.svg",
    link: "https://whoworkswhen.com"
  },
  {
    id: 2,
    name: "DOOH Advertising Platform",
    description: "A platform designed to manage and deliver digital out-of-home advertising content across various screens and locations including mobile app.",
    longDescription: "Revolutionize outdoor advertising with our comprehensive DOOH platform. Reach your audience with targeted, dynamic content across multiple locations and formats.",
    features: ["AI Integration", "Real-time Analytics", "Automated Scheduling", "Location Targeting", "Multi Tenant"],
    tech: ["NextJS", "Tailwind CSS", "Python", "Pytorch", "Django", "PostgreSQL", "Vercel", "Transfer Learning"],
    coverImage: "/products/ad-iq-app.jpg",
    images: [
      "/products/ad-iq.png",
      "/products/ad-iq-app.jpg",
      "/products/ad-iq/ad-iq.png",
      "/products/ad-iq/ad-1.png",
      "/products/ad-iq/ad-2.png",
      "/products/ad-iq/ad-3.png",
      "/products/ad-iq/ad-4.png",
      "/products/ad-iq/aq-1.jpg",
      "/products/ad-iq/aq-2.png",
      "/products/ad-iq/aq-3.jpg",
      "/products/ad-iq/aq-4.png",
      "/products/ad-iq/aq-5.png",
      "/products/ad-iq/aq-6.png",
      "/products/ad-iq/aq-7.png",
      "/products/ad-iq/aq-8.png",
      "/products/ad-iq/aq-9.png",
      "/products/ad-iq/aq-10.png",
      "/products/ad-iq/aph-1.png",
      "/products/ad-iq/aph-2.png",
      "/products/ad-iq/aph-3.png",
      "/products/ad-iq/aph-4.png",
      "/products/ad-iq/aph-5.png",
      "/products/ad-iq/aph-6.png",
      "/products/ad-iq/aph-7.png",
      "/products/ad-iq/aph-8.png",
    ],
    mission: "Empowering businesses to optimize their workforce and drive growth.",
    vision: "To become the leading provider of innovative workforce management solutions.",
    category: "Enterprise Solutions",
    company: "City Group (AD-IQ)",
    companyLogo: "/partners/cg_l.png",
    link: "https://www.behance.net/gallery/123426619/AD-IQ-Listing-Website"
  },
  {
    id: 3,
    name: "Medical AI Platform",
    description: "An advanced platform that utilizes AI to assist healthcare professionals in diagnosing, predicting, and personalizing treatment plans for patients.",
    longDescription: "",
    features: ["Custom Analytics", "AI Prediction", "Cross Platform", "User Management"],
    tech: ["NextJS", "Tailwind CSS", "Python", "Pytorch", "Django", "PostgreSQL", "Vercel", "Transfer Learning"],
    coverImage: "/products/medicalprone.png",
    images: [
      "/products/medicalprone.png",
      "/products/mp/mp-1.png",
      "https://bmmk5ehvex.ufs.sh/f/m9mQBdJCZN5juFb75cHUL2WpeRJyh78139mEYzBaN5HQdCMO",
      "https://bmmk5ehvex.ufs.sh/f/m9mQBdJCZN5j8woy9WpUbcsmGt2wepWykl93LN8ErFaKonx1",
    ],
    mission: "Empowering businesses to optimize their workforce and drive growth.",
    vision: "To become the leading provider of innovative workforce management solutions.",
    category: "Medical Solutions",
    company: "City Group (Asgar Ali Hospital)",
    companyLogo: "/partners/cg_l.png",
    link: "https://medical-prone.vercel.app/"
  },
  {
    id: 4,
    name: "Lienzo - Licensing Platform",
    description: "Simplified software licenses management for businesses.",
    longDescription: "Lienzo is a comprehensive software license management platform designed to simplify the software licensing process for businesses.",
    features: ["Custom Analytics", "AI Prediction", "Cross Platform", "User Management"],
    tech: ["NextJS", "Tailwind CSS", "ShadCN/UI", "SQL"],
    coverImage: "/products/lienzo.png",
    images: [
      "/products/lienzo.png",
      "/products/lienzo/l2.png",
      "/products/lienzo/l3.png",
      "/products/lienzo/l4.png",
      "/products/lienzo/l5.png",
      "/products/lienzo/l6.png",
      "/products/lienzo/l7.png",
      "/products/lienzo/l8.png",
      "/products/lienzo/l9.png",
    ],
    mission: "At Lienzo, our mission is to empower organizations to take control of their software ecosystem. We strive to provide a comprehensive, user-friendly platform that transforms the way businesses acquire, manage, and optimize their software licenses.",
    vision: "To become the leading provider of innovative software asset management solutions.",
    category: "Enterprise Solutions",
    company: "Leinzo",
    companyLogo: "/partners/lienzo-logo.png",
    link: "https://lienzoapp.vercel.app/"
  },
  {
    id: 5,
    name: "Ontario Pulse - Blogging Platform",
    description: "Your trusted source for Ontario news and updates.",
    longDescription: "Stay up-to-date with the latest news and updates from Ontario. Our platform provides a comprehensive and engaging experience for readers.",
    features: ["Static Generation", "MDX", "Cross Platform", "User Management"],
    tech: ["NextJS", "Tailwind CSS", "ShadCN/UI", "MDX"],
    coverImage: "/products/op.png",
    images: [
      "/products/op/op-2.png",
      "/products/op/op-3.png",
      "/products/op/op-1.png",
      "/products/op/op-4.png",
      "/products/op/op-5.png",
    ],
    mission: "Empowering readers with the latest news and updates from Ontario. Our mission is to provide a platform that is accessible, engaging, and informative.",
    vision: "To become the leading source of news and updates from Ontario.",
    category: "Ventures",
    company: "OonkoO",
    companyLogo: "/oonkoo_logo.svg",
    link: "https://www.ontariopulse.com"
  }
];